apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret.yaml
  - secretstore.yaml
  - issuers/cluster-issuer-mkcert.yaml
  - issuers/cluster-issuer-desec-io.yaml
  # Note: Add certificates or secrets folder paths here as you build them out!
