# infrastructure/controllers/cert-manager/base/secretstore.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao-store
  namespace: cert-manager
spec:
  provider:
    vault:
      server: "http://openbao.monitoring.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        # Tip: Use Kubernetes auth for Pod-to-Bao communication
        kubernetes:
          mountPath: "kubernetes"
          role: "cert-manager-role"
          serviceAccountRef:
            name: cert-manager
