apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: false

# Apply common metadata
commonLabels:
  app.kubernetes.io/name: blocky
  app.kubernetes.io/part-of: homelab-infrastructure
