apiVersion: v1
kind: Namespace
metadata:
  name: blocky-namespace # placeholder
  labels:
    # Infrastructure Tiers
    tier: infrastructure
    component: dns
    # Security/Governance Labels (The "Senior" addition)
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest

  annotations:
    # Documentation & Ownership
    home.lab/owner: "aner"
    home.lab/description: "Primary DNS resolution for the homelab"
    # Automation (Example: Goldilocks or VPA)
    goldilocks.cloud.google.com/check: "true"
