apiVersion: v1
kind: ServiceAccount
metadata:
  name: blocky-sa
  namespace: blocky
  labels:
    app.kubernetes.io/name: blocky
    app.kubernetes.io/part-of: infrastructure

# Tip: Disable API token mounting if the app doesn't call K8s API directly.
# This aims to reduce the "Blast Radius" if the Pod is compromised.
automountServiceAccountToken: false
