---
apiVersion: v1
kind: Secret
metadata:
  name: flux-system
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBj6BHJheOmRtaSRdZ0EFyDzsCPyrOpXyZVk6knlUIH+AAAAJhh6dhsYenY
    bAAAAAtzc2gtZWQyNTUxOQAAACBj6BHJheOmRtaSRdZ0EFyDzsCPyrOpXyZVk6knlUIH+A
    AAAEAZ5uSpPmOWaA2/VJ3SZr2w1mEpvqAlwcCmTPV/v3HkS2PoEcmF46ZG1pJF1nQQXIPO
    wI/Ks6lfJlWTqSeVQgf4AAAAEGZsdXgtaG9tZWxhYi1ib3QBAgMEBQ==
    -----END OPENSSH PRIVATE KEY-----
  identity.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGPoEcmF46ZG1pJF1nQQXIPOwI/Ks6lfJlWTqSeVQgf4
  known_hosts: codeberg.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBL2pDxWr18SoiDJCGZ5LmxPygTlPu+cCKSkpqkvCyQzl5xmIMeKNdfdBpfbCGDPoZQghePzFZkKJNR/v9Win3Sc=

