apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# CHANGED: Swapped out the raw Git repository folder for the single flat file bundle stream
resources:
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.11/deploy/crds/bundle.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: platform-foundation
      managed-by: flux

commonAnnotations:
  homelab.local/layer: layer-01-crds
