apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  # reference the Flux Kustomization objects defined in this folder
  - 01-crds.yaml
  - 02-controllers.yaml
  - 03-secrets.yaml
  - 04-applications.yaml
  - 05-ingress.yaml
