apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-release.yaml
  - helm-repository.yaml

configMapGenerator:
  - name: blocky-config
    files:
      - config.yaml

generatorOptions:
  disableNameSuffixHash: false

# Apply common metadata
labels:
  - pairs:
      app.kubernetes.io/name: blocky
      app.kubernetes.io/part-of: homelab-infrastructure
