apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: desec-credentials
  namespace: cert-manager
spec:
  refreshInterval: "1h" # How often to check OpenBao for updates
  secretStoreRef:
    name: openbao-store # Must match your SecretStore name
    kind: SecretStore
  target:
    name: desec-credentials # The name of the K8s Secret to be CREATED
    creationPolicy: Owner
  data:
    - secretKey: token # The key inside the K8s Secret
      remoteRef:
        key: athanor/desec # Removed secret/data/
        property: token # The key inside the OpenBao JSON/KV
