# apps/linkding/base/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: linkding-env-secrets # This secret will be created in K8s
    creationPolicy: Owner
    deletionPolicy: Delete # Ensure the secret is cleaned up if the ES is deleted
  data:
    - secretKey: LD_SUPERUSER_PASSWORD
      remoteRef:
        key: apps/linkding/production
        property: admin_password
