# apps/observability/gotify/base/security/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gotify-secrets
  namespace: gotify
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao-global-store
    kind: ClusterSecretStore
  target:
    name: gotify-app-credentials # The name of the native Secret ESO will generate
    creationPolicy: Owner
  data:
    - secretKey: gotify-admin-password
      remoteRef:
        key: homelab/observability/gotify
        property: admin_password
