apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - resources/http-route.yaml

patches:
  - path: patches/ryzen-v2-engine.yaml
    target:
      kind: HelmRelease
      name: longhorn
