apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: athanor-autoscrape
  namespace: observability
spec:
  # use a `label selector` to attach the creation of an scrape at the application level
  selector:
    matchLabels:
      athanor.io/scrape: "true"
  endpoints:
    - port: "http" # Common for Linkding
      path: /metrics
    - port: "metrics" # Common for exporters/Go apps
      path: /metrics
