apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: athanor-metrics-db
  namespace: observability
spec:
  image:
    repository: victoriametrics/victoria-metrics
    tag: v1.139.0
  # imagePullSecrets:              # Uncomment once Harbor is operational
  #   - name: harbor-pull-secret   # Created via: kubectl create secret docker-registry...
  retentionPeriod: "3"
  ingestOnlyMode: false

  # STORAGE MANAGEMENT
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: longhorn

  vmBackup:
    # Point this to RustFS S3 bucket
    destination: "s3://backups/athanor-metrics"
    # This refers to the 'target' name in the ExternalSecret
    credentialsSecret:
      name: vm-auth-credentials
      key: RUSTFS_S3_CONFIG

    customArgs:
      - "-s3.endpoint=http://rustfs-service.rustfs-namespace.svc.cluster.local:\
        9000"
      - "-s3.forcePathStyle=true" # Often needed for self-hosted S3 like RustFS

  resources:
    limits:
      cpu: "500m"
      memory: "1000Mi"
    requests:
      cpu: "100m"
      memory: "500Mi"
