apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: blocky-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend # References a ClusterSecretStore managed elsewhere
    kind: ClusterSecretStore
  target:
    name: blocky-auth-credentials # The name of the K8s Secret that WILL be created
    creationPolicy: Owner # Critical for avoiding Zombies
  data:
    - secretKey: UPSTREAM_TOKEN
      remoteRef:
        key: homelab/network/blocky
        property: api_token
