apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - external-secret.yaml

commonLabels:
  environment: production
  secret-access/vault: "true"

patches:
  - target:
      kind: Namespace
      name: blocky
    patch: |-
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
        value: restricted

images:
  - name: blocky
    newName: ghcr.io/0xerr0r/blocky
    newTag: v0.28.2

configMapGenerator:
  - name: blocky-config
    behavior: replace
    files:
      - config.yaml=config.yaml
