apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-backup-target-s3
  namespace: longhorn-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: garage-s3-auth # Longhorn will look for this name
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secret/data/infra/garage
        property: access_key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/data/infra/garage
        property: secret_key
