apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: ingress-localpath-internal
  namespace: localpath
spec:
  endpointSelector: {} # Applies to all pods in the namespace
  egress:
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": localpath
  # Note: Ingress is usually not needed unless they expose a service (like the webhook)
