apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-layer
  namespace: flux-system
spec:
  interval: 1h
  path: ./infrastructure
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
