# infrastructure/controllers/cilium/base/patches/harden-operator-secrets.yaml
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: cilium-operator
# rules:
#   - apiGroups: [""]
#     resources: ["secrets"]
#     # Stripping 'create', 'update', 'patch', 'delete' to reduce blast radius.
#     # Retaining only 'get', 'list', 'watch' for read-only connectivity check.
#     verbs: ["get", "list", "watch"]
