# clusters/athanor/02-controllers.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: layer-02-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: layer-01-crds

  interval: 15m
  retryInterval: 2m
  path: ./infrastructure/controllers
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system

  # --- PRODUCTION METADATA ---
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: platform-foundation
      app.kubernetes.io/component: controllers
      app.kubernetes.io/managed-by: flux
    annotations:
      athanor.io/owner: "aner"
      athanor.io/description: "Core operators and binaries that manage cluster functionality."
