# infrastructure/crds/external-secrets/sync.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: src-cilium
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/cilium/cilium
  ref:
    tag: v1.19.1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-crds-cilium
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  path: pkg/k8s/apis/cilium.io/client/crds
  sourceRef:
    kind: GitRepository
    name: src-cilium
  targetNamespace: flux-system
  # Common metadata helps me find resources in 'k9s' or 'kubectl'
  commonMetadata:
    labels:
      managed-by: flux
      app.kubernetes.io/part-of: homelab-infrastructure
