apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: blocky-secrets
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: openbao-store # References the ClusterSecretStore (declared in 'external-secrets/')
    kind: ClusterSecretStore
  target:
    name: blocky-auth-credentials # The name of the K8s Secret that will be created
    creationPolicy: Owner
  data:
    - secretKey: BLOCKY_TOKEN
      remoteRef:
        # Match the Tofu pattern: see -> `kv_apps.tf`
        key: apps/blocky/production # Removed secret/data/
        property: api_token
