# infrastructure/controllers/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium/base
  - external-secrets/base
  - cert-manager/base
  - eso/base
  - traefik/base
  - cloudnative-pg/base
  - local-path/base
