# infrastructure/controllers/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium/production
  - longhorn/production
  - local-path/production
  - external-secrets/production
  - cert-manager/production
  - eso/production
  - cloudnative-pg/production
  - traefik/production
