# infrastructure/crds/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager/sync.yaml
  - cilium/sync.yaml
  - cloudnative-pg/sync.yaml
  - gateway/sync.yaml
  - external-secrets/sync.yaml
  - longhorn/sync.yaml
