# infrastructure/controllers/cert-manager/base/clusterissuer.yaml
# THE EXTERNAL DOOR (ACME/Let's Encrypt)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@domain.com
    privateKeySecretRef:
      name: letsencrypt-production-account-key
    profile: classic
    solvers:
      - selector:
        dnsNames:
          - "*.yourdomain.com"
          - "yourdomain.com"
        dns01:
          webhook:
            groupName: acme.desec.io
            solverName: desec
            config:
              apiTokenSecretRef:
                name: desec-api-token
                key: api-token
      # FALLBACK/GENERIC: HTTP-01 for everything else
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: traefik-gateway
                namespace: traefik
                kind: Gateway
            serviceType: ClusterIP

---
# THE INTERNAL DOOR (Vault/OpenBao)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki/sign/homelab-dot-local # Path in your OpenBao PKI engine
    server: http://openbao-active.openbao.svc.cluster.local:8200
    auth:
      kubernetes:
        role: cert-manager-issuer-role
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: cert-manager
