apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: desec-api-credentials
  namespace: cert-manager
spec:
  refreshInterval: "1h" # Set a reasonable refresh for rotation
  secretStoreRef:
    name: openbao-backend # This must match the name in base/secretstore.yaml
    kind: ClusterSecretStore
  target:
    name: desec-api-token # K8s Secret name that will be created
    creationPolicy: Owner
  data:
    - secretKey: api-token # The key inside the K8s Secret
      remoteRef:
        # Follows the Tofu naming-convention: {mount}/data/apps/{app_name}/{env}
        key: secret/data/athanor/desec # Path in Openbao
        property: api-token # key inside OpenBao
