apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openbao-backend
spec:
  conditions:
    - namespaceSelector:
        matchLabels:
          secret-access/vault: "enabled" # this label should be in each '<APP>/namespace.yaml' of all applications
  provider:
    vault:
      server: "http://openbao-active.openbao.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes" # Matches vault_auth_backend.kubernetes.path
          role: "external-secrets-role" # Matches vault_kubernetes_auth_backend_role.external_secrets.role_name
          serviceAccountRef:
            name: "external-secrets" # This MUST match the string declared in Tofu's apps_config map" (base/variables.tf)
            namespace: "external-secrets"
