apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headscale-operator
  namespace: flux-system
spec:
  interval: 2h
  url: oci://ghcr.io/infradohq/headscale-operator/charts
