apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik-crds
      version: "1.16.*" # Note: CRD versions follow a different track than the app
      sourceRef:
        kind: HelmRepository
        name: traefik-oci
        namespace: flux-system
  install:
    crds: CreateReplace # Flux manages the CRD lifecycle
  upgrade:
    crds: CreateReplace
