apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - storage/
  - postgres/
  - garage/
  - openbao/

# Common labels help you identify 'Athanor' config resources
commonLabels:
  app.kubernetes.io/managed-by: "flux"
