# infrastructure/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/
  - controllers/ # This should point to infrastructure/controllers/kustomization.yaml
  - storage/ # This should point to infrastructure/storage/kustomization.yaml
  - gateway-api/
