apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-forgejo
  namespace: database-system
spec:
  inheritedMetadata:
    labels:

  # MANDATORY: 1 instance for a single-node k3s environment
  instances: 1

  # DETERMINISM: Pinning the major version
  imageName: ghcr.io/cloudnative-pg/postgresql:17.9-202603230821-system-trixie

  # STORAGE: Explicitly routing to your CSI
  storage:
    size: 10Gi
    storageClass: longhorn

  # RESOURCES
  # Gating this to 1Gi ensures my 32GB RAM is preserved for other apps
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1"

  # POSTGRESQL: Engine-level tuning
  postgresql:
    parameters:
      # Postgres relies heavily on the OS cache.
      # Setting this to ~25% of the pod's RAM limit is the optimal standard.
      shared_buffers: "256MB"
      max_connections: "100"

  # BOOTSTRAP: Declarative DB creation
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      # The operator will automatically generate a secret named 'db-forgejo-app'
      # containing the password for this user.

  # S3 STORAGE BACKUP: Future garage deployment
  # backup:
  #   barmanObjectStore:
  #     destinationPath: "s3://backups/athanor/"
  #     endpointURL: "http://garage-service.storage-system.svc.cluster.local:3900" # Your Garage endpoint
  #     s3Credentials:
  #       accessKeyId:
  #         name: garage-creds
  #         key: ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: garage-creds
  #         key: ACCESS_SECRET_KEY

  # MONITORING: Expose Prometheus metrics natively
  monitoring:
    enablePodMonitor: true
