# infrastructure/configs/observability/node-scrape.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: node-exporter
  namespace: observability
spec:
  # This tells VMAgent to find nodes that are "Ready"
  selector:
    matchLabels:
      kubernetes.io/os: linux
  # The path where node-exporter serves data
  path: /metrics
  # Port 9100 (which you defined in your HelmRelease)
  port: "9100"
  interval: 30s
  relabelConfigs:
    # Senior Habit: Rename the 'instance' from the internal IP to the actual Node Name
    - sourceLabels: [__meta_kubernetes_node_name]
      targetLabel: instance
