apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  # Using the Recommended OCI Registry
  chart: oci://quay.io/cilium/charts/cilium
  version: "1.19.1"
  targetNamespace: kube-system
  valuesContent: |
    # Match K3s default podCIDR
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]

    # Required for K3s/eBPF logic
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    kubeProxyReplacement: true

    # Direct Routing for the "Production" feel
    routingMode: native
    autoDirectNodeRoutes: true

    # Enable L2 Announcements (To replace MetalLB later)
    l2announcements:
      enabled: true
