# apps/linkding/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ./base/kustomization.yaml
resources:
  - ../base

# Identity defines WHO the app is (Stable for Selectors)
commonLabels:
  app.kubernetes.io/name: linkding
  app.kubernetes.io/part-of: athanor-core
