apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 1. Reach across the distance to inherit the abstract logic
  - ../base

  # 2. Pull in your local encrypted production payload
  - security/secrets/mkcert-root-ca-secret.enc.yaml
