apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-smoketest
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: k8s-test-secret # This is the name of the final K8s Secret
    creationPolicy: Owner
  data:
    - secretKey: my-password-key # The key name inside the K8s Secret
      remoteRef:
        key: secret/test-secret
        property: password # Matches the key you used in 'vault kv put'
